package br.com.crud.telas;

import java.awt.Color;
public class FrameInicial extends javax.swing.JFrame {
    public FrameInicial() {
        initComponents();
        panelCadastro.setVisible(false);
        panelMinhaLoja.setVisible(false);
        panelPedido.setVisible(false);
        txtUserName.setText("admin");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelPedido = new javax.swing.JPanel();
        lblBalcao = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        lblRetirada = new javax.swing.JLabel();
        panelCadastro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelMinhaLoja = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelpedidoazul = new javax.swing.JPanel();
        txtPedidoazul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelpedidoazul1 = new javax.swing.JPanel();
        txtPedidoazul1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelpedidoazul2 = new javax.swing.JPanel();
        txtPedidoazul2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelpedidoazul3 = new javax.swing.JPanel();
        txtPedidoazul3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 27, 32));

        jPanel2.setBackground(new java.awt.Color(34, 45, 49));
        jPanel2.setForeground(new java.awt.Color(34, 40, 44));

        panelPedido.setBackground(new java.awt.Color(47, 55, 62));
        panelPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPedidoMouseClicked(evt);
            }
        });

        lblBalcao.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        lblBalcao.setForeground(new java.awt.Color(255, 255, 255));
        lblBalcao.setText("Balcão");

        lblEntrega.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        lblEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrega.setText("Entrega");

        lblRetirada.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        lblRetirada.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirada.setText("Retirada");

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRetirada)
                    .addComponent(lblEntrega)
                    .addComponent(lblBalcao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBalcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCadastro.setBackground(new java.awt.Color(47, 55, 62));

        jLabel9.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clientes");

        jLabel10.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Produtos");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Funcionarios");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        panelMinhaLoja.setBackground(new java.awt.Color(47, 55, 62));

        jLabel12.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Relatorio");

        javax.swing.GroupLayout panelMinhaLojaLayout = new javax.swing.GroupLayout(panelMinhaLoja);
        panelMinhaLoja.setLayout(panelMinhaLojaLayout);
        panelMinhaLojaLayout.setHorizontalGroup(
            panelMinhaLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMinhaLojaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMinhaLojaLayout.setVerticalGroup(
            panelMinhaLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMinhaLojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpedidoazul.setBackground(new java.awt.Color(34, 45, 49));
        panelpedidoazul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpedidoazulMouseClicked(evt);
            }
        });

        txtPedidoazul.setBackground(new java.awt.Color(255, 255, 255));
        txtPedidoazul.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        txtPedidoazul.setForeground(new java.awt.Color(204, 204, 204));
        txtPedidoazul.setText("Pedido");
        txtPedidoazul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPedidoazulMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/hambúrguerCCCCCC.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/SetaCCCCCC.png"))); // NOI18N

        javax.swing.GroupLayout panelpedidoazulLayout = new javax.swing.GroupLayout(panelpedidoazul);
        panelpedidoazul.setLayout(panelpedidoazulLayout);
        panelpedidoazulLayout.setHorizontalGroup(
            panelpedidoazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazulLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPedidoazul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
        );
        panelpedidoazulLayout.setVerticalGroup(
            panelpedidoazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazulLayout.createSequentialGroup()
                .addGroup(panelpedidoazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedidoazulLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(panelpedidoazulLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addComponent(txtPedidoazul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpedidoazul1.setBackground(new java.awt.Color(34, 45, 49));
        panelpedidoazul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpedidoazul1MouseClicked(evt);
            }
        });

        txtPedidoazul1.setBackground(new java.awt.Color(255, 255, 255));
        txtPedidoazul1.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        txtPedidoazul1.setForeground(new java.awt.Color(204, 204, 204));
        txtPedidoazul1.setText("Cadastro");
        txtPedidoazul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPedidoazul1MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/maisCCCCCC.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/SetaCCCCCC.png"))); // NOI18N

        javax.swing.GroupLayout panelpedidoazul1Layout = new javax.swing.GroupLayout(panelpedidoazul1);
        panelpedidoazul1.setLayout(panelpedidoazul1Layout);
        panelpedidoazul1Layout.setHorizontalGroup(
            panelpedidoazul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtPedidoazul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(12, 12, 12))
        );
        panelpedidoazul1Layout.setVerticalGroup(
            panelpedidoazul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul1Layout.createSequentialGroup()
                .addGroup(panelpedidoazul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedidoazul1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addGroup(panelpedidoazul1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13))
                    .addComponent(txtPedidoazul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpedidoazul2.setBackground(new java.awt.Color(34, 45, 49));
        panelpedidoazul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpedidoazul2MouseClicked(evt);
            }
        });

        txtPedidoazul2.setBackground(new java.awt.Color(255, 255, 255));
        txtPedidoazul2.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        txtPedidoazul2.setForeground(new java.awt.Color(204, 204, 204));
        txtPedidoazul2.setText("Minha loja");
        txtPedidoazul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPedidoazul2MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/lojaCCCCCC.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/SetaCCCCCC.png"))); // NOI18N

        javax.swing.GroupLayout panelpedidoazul2Layout = new javax.swing.GroupLayout(panelpedidoazul2);
        panelpedidoazul2.setLayout(panelpedidoazul2Layout);
        panelpedidoazul2Layout.setHorizontalGroup(
            panelpedidoazul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txtPedidoazul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(12, 12, 12))
        );
        panelpedidoazul2Layout.setVerticalGroup(
            panelpedidoazul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul2Layout.createSequentialGroup()
                .addGroup(panelpedidoazul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedidoazul2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15))
                    .addGroup(panelpedidoazul2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel16))
                    .addComponent(txtPedidoazul2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpedidoazul3.setBackground(new java.awt.Color(34, 45, 49));
        panelpedidoazul3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpedidoazul3MouseClicked(evt);
            }
        });

        txtPedidoazul3.setBackground(new java.awt.Color(255, 255, 255));
        txtPedidoazul3.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        txtPedidoazul3.setForeground(new java.awt.Color(204, 204, 204));
        txtPedidoazul3.setText("Configurações");
        txtPedidoazul3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPedidoazul3MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/configuraçõesCCCCCC.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/SetaCCCCCC.png"))); // NOI18N

        javax.swing.GroupLayout panelpedidoazul3Layout = new javax.swing.GroupLayout(panelpedidoazul3);
        panelpedidoazul3.setLayout(panelpedidoazul3Layout);
        panelpedidoazul3Layout.setHorizontalGroup(
            panelpedidoazul3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtPedidoazul3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(12, 12, 12))
        );
        panelpedidoazul3Layout.setVerticalGroup(
            panelpedidoazul3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidoazul3Layout.createSequentialGroup()
                .addGroup(panelpedidoazul3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedidoazul3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17))
                    .addGroup(panelpedidoazul3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel18))
                    .addComponent(txtPedidoazul3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(204, 204, 204));
        txtUserName.setText("Usuario");
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensCCCCCC/UsuarioCCCCCC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelpedidoazul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelpedidoazul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelpedidoazul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelpedidoazul3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMinhaLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpedidoazul, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpedidoazul1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpedidoazul2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMinhaLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpedidoazul3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 372, 968);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPedidoazulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPedidoazulMouseClicked
        panelpedidoazul.setBackground(new Color(1,116,175));
        txtPedidoazul.setForeground(new Color(255,255,255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensBrancas/hambúrguerBranco.png")));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensBrancas/SetaBrancaBaixo.png")));
        panelPedido.setVisible(true);       
        
        
    }//GEN-LAST:event_txtPedidoazulMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       //tela do arthur FrameCred tela = new FrameCred();
        //tela.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void panelpedidoazulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpedidoazulMouseClicked
        panelpedidoazul.setBackground(new Color(1,116,175));
        txtPedidoazul.setForeground(new Color(255,255,255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensBrancas/hambúrguerBranco.png")));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensBrancas/SetaBrancaBaixo.png")));
        panelPedido.setVisible(true);
        
    }//GEN-LAST:event_panelpedidoazulMouseClicked

    private void txtPedidoazul1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPedidoazul1MouseClicked
        
        
        
    }//GEN-LAST:event_txtPedidoazul1MouseClicked

    private void panelpedidoazul1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpedidoazul1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpedidoazul1MouseClicked

    private void txtPedidoazul2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPedidoazul2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidoazul2MouseClicked

    private void panelpedidoazul2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpedidoazul2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpedidoazul2MouseClicked

    private void txtPedidoazul3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPedidoazul3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidoazul3MouseClicked

    private void panelpedidoazul3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpedidoazul3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpedidoazul3MouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void panelPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBalcao;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblRetirada;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelMinhaLoja;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JPanel panelpedidoazul;
    private javax.swing.JPanel panelpedidoazul1;
    private javax.swing.JPanel panelpedidoazul2;
    private javax.swing.JPanel panelpedidoazul3;
    private javax.swing.JLabel txtPedidoazul;
    private javax.swing.JLabel txtPedidoazul1;
    private javax.swing.JLabel txtPedidoazul2;
    private javax.swing.JLabel txtPedidoazul3;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
